### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [andy059120/git-practice#1]
作業做得很好，可以公開發表成 blog 文章。

一個小地方: 善用圖片協助表達 --> 我有看到你有放 asset/img，但為什麼沒有把圖片嵌進 md 文件中輔助說明？

**Comment by andy059120** [comment]
謝謝老師的回饋和肯定。

當時作業寫到稍顯疲倦，來不及把圖片好好表示。我會再做排版上的修改，讓文章更好讀，感謝。

**Comment by azole** [comment]
了解，謝謝回覆，之後的作業再調整就好（當然，如果你要回頭調整 git 這份作業，也很好，一如課堂上說的，好好整理好，就去公開發表吧！）

如果沒有其他要跟我討論的部分，這個 issue 就可以先 close 了。
